### PR TITLE
ssh-key: make `decode_as` a public API 

### PR DESCRIPTION
**Pull request by baloo**
When parsing ssh keys from the SSH agent protocol, you need to read the first element of the protocol (the [`ssh_key::Algorithm`](https://docs.rs/ssh-key/latest/ssh_key/enum.Algorithm.html) (encoded as a String) to make a decision whether what comes next is supposed to be parsed as an [`ssh_key::Certificate`](https://docs.rs/ssh-key/latest/ssh_key/certificate/struct.Certificate.html) or as an [`ssh_key::private::KeypairData`](https://docs.rs/ssh-key/latest/ssh_key/private/enum.KeypairData.html).

Because the content has already been consumed from the reader, and because you can't go backwards in the reader. This requires `decode_as` to be exposed on `ssh_key::private::KeypairData`.

### CODE REVIEW

**Comment by baloo** [comment]
I'd love to have this backported and released to a `ssh-key/v0.6.6`

**Comment by wiktor-k** [comment]
Great to see this filed! Thanks a lot @baloo :bow: 

I think in general all these "first string ID (algorithm), then we decide what to do" should have a `decode_as` variants or maybe even all uses of `KeypairData` should be inspected. If SSH sends us certificates instead of keys during SSH agent protocol it may do so in other places too.

In other words the [`Credential` type](https://github.com/wiktor-k/ssh-agent-lib/pull/33/files#diff-df072ef19672423882be4a4765c6031c0d533da1d90a63cf1310e24ac11f54eeR102) that was added to the SSH agent crate may as well be useful for other people and maybe it's place is here?

And if so the question is what to do with other types which are used in SSH agent protocol. Maybe they could also be moved here after they "stabilize" a bit?

This is all just ideas for far future but in the short-term it'd be really nice to have this merged. :pray: 

Thanks for your time! :wave:

**Comment by baloo** [comment]
> In other words the [`Credential` type](https://github.com/wiktor-k/ssh-agent-lib/pull/33/files#diff-df072ef19672423882be4a4765c6031c0d533da1d90a63cf1310e24ac11f54eeR102) that was added to the SSH agent crate may as well be useful for other people and maybe it's place is here?

I don't think it will be ever used outside the agent protocol. This is only used because encoding of private keys changes whether they are tied to certificates or not. I believe agent protocol is the only one that involves private keys.

**Comment by tarcieri** [comment]
Are you suggesting a new method, or if not, can you link in the source code to the method you're talking about?

As far as I can tell, there is no `decode_as` method defined on `ssh_key::private::KeypairData` at present, only on `ssh_key::public::KeyData`.

**Comment by baloo** [comment]
https://github.com/wiktor-k/ssh-agent-lib/pull/33/files#r1554798031

**Comment by wiktor-k** [comment]
> Are you suggesting a new method, or if not, can you link in the source code to the method you're talking about?
> 
> As far as I can tell, there is no `decode_as` method defined on `ssh_key::private::KeypairData` at present, only on `ssh_key::public::KeyData`.

I'm not sure if I got you right but we need this PR (which adds the decode_as method) in the downstream ssh agent crate: https://github.com/wiktor-k/ssh-agent-lib/pull/33/files#r1554798031

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
